// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package referentialintegrity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	Sid      int32
	Cname    string
	Major    pgtype.Text
	Decision pgtype.Text
}

type College struct {
	Cname      string
	State      pgtype.Text
	Enrollment pgtype.Int4
}

type Student struct {
	Sid    int32
	Sname  pgtype.Text
	Gpa    pgtype.Float4
	Sizehs pgtype.Int4
}
